repos:
- repo: local
  hooks:
    - id: git-secrets
      name: Git Secrets
      description: git-secrets scans commits, commit messages, and --no-ff merges to prevent adding secrets into your git repositories.
      entry: /workspaces/git-secrets/git-secrets
      args: ['--pre_commit_hook']
      language: system
