name: merge to main workflow

on:
  push:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.ref.BRANCH_NAME }}

jobs:
  get_commit_id:
    runs-on: ubuntu-22.04
    outputs:
      commit_id: ${{ steps.commit_id.outputs.commit_id }}
      sha_short: ${{ steps.commit_id.outputs.sha_short }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Get Commit ID
        id: commit_id
        run: |
          #  echo "commit_id=${{ github.sha }}" >> "$GITHUB_ENV"
          echo "commit_id=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
  get_asdf_version:
    runs-on: ubuntu-22.04
    outputs:
      asdf_version: ${{ steps.asdf-version.outputs.version }}
      tag_format: ${{ steps.load-config.outputs.TAG_FORMAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get asdf version
        id: asdf-version
        run: echo "version=$(awk '!/^#/ && NF {print $1; exit}' .tool-versions.asdf)" >> "$GITHUB_OUTPUT"
      - name: Load config value
        id: load-config
        run: |
          TAG_FORMAT=$(yq '.TAG_FORMAT' .github/config/settings.yml)
          echo "TAG_FORMAT=$TAG_FORMAT" >> "$GITHUB_OUTPUT"
  quality_checks:
    needs: [get_asdf_version, get_commit_id]
    uses: ./.github/workflows/quality-checks.yml
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.asdf_version }}
      dev_container_ecr: dev-container-quality-checks
      dev_container_image_tag: release-${{ needs.get_commit_id.outputs.sha_short }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PUSH_IMAGE_ROLE: ${{ secrets.PUSH_IMAGE_ROLE }}
  tag_release:
    needs: [quality_checks, get_asdf_version]
    uses: NHSDigital/eps-workflow-semantic-release/.github/workflows/tag-release.yml@f80157cecce288dd175e61b477a1d2dbe9c88b99
    with:
      dry_run: false
      asdfVersion: ${{ needs.get_asdf_version.outputs.asdf_version }}
      branch_name: main
      publish_package: false
      tag_format: ${{ needs.get_asdf_version.outputs.tag_format }}
    secrets: inherit
